//exports.Group = require('./group')
exports.Szenario = require('./szenario')
exports.NewPath = require('./newPath')
exports.ActualPosition = require('./actualPosition')
exports.Config = require('./config')